export interface ResultsPoints {
  stage_id: number,
  rider_participation_id: number,
  stagepos: number,
  gcpos: number,
  pointspos: number,
  kompos: number,
  yocpos: number,
  stagescore: number,
  gcscore: number,
  pointsscore: number,
  komscore: number,
  yocscore: number,
  teamscore: number,
  totalscore: number,
  stageresult: string,
  gcresult: string,
  pointsresults: number,
  komresult: number,
  yocresult: string,
  gcchange: string,
  pointsprev: number,
  pointschange: string,
  komprev: number,
  komchange: string,
  yocprev: number,
  yocchange: string,
}